# .github/workflows/link-check.yml
name: Check Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly check on Sunday

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: --verbose --no-progress --accept 200,204,206,301,302,304 **/*.md
          fail: true
        
      - name: Create Issue From File
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: |
            broken-links
            automated
